default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taster_development
  host: localhost

test:
  <<: *default
  database: taster_test
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
